"""empty message

Revision ID: 330f465e5b02
Revises: 3c384c96c051
Create Date: 2020-01-26 12:30:22.350568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330f465e5b02'
down_revision = '3c384c96c051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_constraint_user_pdf', 'post', ['user_id', 'pdf_id'])
    op.drop_table_comment(
        'post',
        existing_comment='帖子信息',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'post',
        '帖子信息',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('unique_constraint_user_pdf', 'post', type_='unique')
    # ### end Alembic commands ###
