"""empty message

Revision ID: 8000cccf3c56
Revises: 4580ceb1a0bf
Create Date: 2020-01-25 22:12:28.190999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8000cccf3c56'
down_revision = '4580ceb1a0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False, comment='PDF主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='PDF书名'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='PDF链接'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='时间截点'),
    sa.Column('create_user_id', mysql.BIGINT(unsigned=True), nullable=True, comment='创建用户'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='PDF信息'
    )
    op.create_table('pdf_group',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False, comment='用户所属组主键'),
    sa.Column('pdf_id', mysql.BIGINT(unsigned=True), nullable=True, comment='PDF'),
    sa.Column('group_id', mysql.BIGINT(unsigned=True), nullable=True, comment='用户组'),
    sa.Column('create_user_id', mysql.BIGINT(unsigned=True), nullable=True, comment='创建用户'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_id', 'group_id', name='pdf_group_unique_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_group')
    op.drop_table('pdf')
    # ### end Alembic commands ###
