"""empty message

Revision ID: c95edecc5f4d
Revises: 8000cccf3c56
Create Date: 2020-01-25 22:14:23.648808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c95edecc5f4d'
down_revision = '8000cccf3c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_group',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False, comment='PDF所属组主键'),
    sa.Column('pdf_id', mysql.BIGINT(unsigned=True), nullable=True, comment='PDF'),
    sa.Column('group_id', mysql.BIGINT(unsigned=True), nullable=True, comment='用户组'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_id', 'group_id', name='pdf_group_unique_constraint'),
    comment='PDF-用户组'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_group')
    # ### end Alembic commands ###
